### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 47

### ISSUE THREAD

**Issue by shivamindalkar** [local-npm/local-npm#130]
Error: Module version mismatch. Expected 48, got 47.
  at Error (native)
  at Object.Module._extensions..node (module.js:597:18)
  at Module.load (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at bindings (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/libxmljs/lib/bindings.js:1:99)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/libxmljs/index.js:4:16)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp-xml-editor/index.js:3:19)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at requireFn (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp-load-plugins/index.js:47:14)
  at Object.get (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp-load-plugins/index.js:84:18)
  at Gulp.<anonymous> (/home/hp/tnex/pollinate-v4/ui/tasks/subtasks/prepareNative.coffee:16:16)
  at module.exports (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/index.js:134:8)
  at /home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp/bin/gulp.js:129:20
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

**Comment by gabrielcsapo** [comment]
@shivamindalkar this usually happens when you switch node versions after you have built c++ binaries using another node engine. IE moving from node 4 to 6. A simple way to fix this is to run `npm rebuild`
