### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5080

### ISSUE THREAD

**Issue by megamindbrian** [local-npm/local-npm#144]
I am trying to use npm a part of Docker, is there a way to get npm to not resolve to localhost and the full domain name of my machine instead?

**Comment by gabrielcsapo** [comment]
@megamindbrian can you specify your environment you are running in?

**Comment by wmhilton** [comment]
Hey @megamindbrian ! Just to clarify, this is the `local-npm` registry server, not the actual [npm](https://github.com/npm/npm). With that said, assuming you are trying to run `local-npm` in docker, I'd suggest trying the instructions I made [here](https://github.com/wmhilton/modserv#run-as-a-docker-container-prefered-method) for `modserv`. (`modserv` is a fork of `local-npm` but is in the process of being [reabsorbed](https://github.com/local-npm/local-npm/pull/140).) If running `modserv` in Docker works for you, then I'll hurry to add 1st class support for Docker back into `local-npm`. :)

**Comment by megamindbrian** [comment]
Running a build inside of docker. I fixed it by combining this package with
npm-proxy-server package.

**Comment by gabrielcsapo** [comment]
@megamindbrian would you be able to provide that information here so we can update the wiki or readme as a way to do that! 😄

**Comment by megamindbrian** [comment]
I don't know if this is a common use case, but I was tired of my Docker
images taking so long.

https://www.npmjs.com/package/npm-proxy-cache

Maybe you can combine forces with this project and offer a proxy in
addition to the nice PouchDB features?

The part that makes local-npm and npm-proxy-cache feel kind of hacky is
inside a Docker build.


```
RUN npm config set proxy http://<fqdn instead of localhost>:8080
RUN npm config set https-proxy http://<fqdn instead of localhost>:8080
RUN npm config set registry http://<fqdn instead of localhost>:5080
RUN npm config set strict-ssl false
```

**Comment by megamindbrian** [comment]
Also the docs only refer to localhost, but I could see this as an in office
package data store.  Sounds like M$ is moving to Github instead of TFS,
might be a good time to prove how much better npm is by joining forces with
a SaaS?  (Service-as-a-service?)

**Comment by gabrielcsapo** [comment]
@megamindbrian thank you for your insight into the problem 😄

I just started maintaining with @wmhilton and we are looking to bring the project back up to speed. 

I see npm-proxy-cache was made by @runk, would you be able to maybe give some direction into seeing how these two projects can merge into one? 

@megamindbrian what do you mean by joining forces with a SaaS? Do you mean a hosted version of this? I would really like to see this have capabilities of being able to deal with publishing packages to local-npm specifically, instead of as a pass through to be honest, is that on par with what you mean by `office package data store`?

**Comment by megamindbrian** [comment]
Sorry.  Just seeing this.  Yes, I meant the scenario in a corporate
environment where many devs could be retrieving packages from a cached but
updated local-store.  I am not sure what features are missing between
local-npm and npm-proxy-cache, I just know that I needed both in order to
use a proxy inside the Docker build process.  It wouldn't connect when to
local-npm unless I also set the NPM proxy config setting.

My understanding is this:

local-npm - responsible for downloading and caching npm index.  Stores
versions and files locally for whatever packages are retrieved.

npm-proxy-cache - responsible for providing a proxy HTTP connection.
Determining whether to retrieve package from remote, or local address.

Running inside of docker, the proxy HTTP allowed me to connect to
local-npm, this meant that npm-proxy-cache was redundant.  If it was
retrieving from remote it would try to get 127.0.0.1 because that was set
in the config, it if was trying from cache it would connect to local-npm
server (also 127.0.0.1).

I think local-npm is missing an HTTP proxy server.  If local-npm provided a
proxy connection as well as indexing, this tool could be used for more
use-cases without any other packages.

**Comment by gabrielcsapo** [comment]
@megamindbrian yeah I totally agree this is a valid scenario. I am seeing valid proxy abilities in local-npm https://github.com/local-npm/local-npm/blob/master/lib/index.js#L72 would you be able to help figure out the feature parity that is needed to achieve what you are asking? 😄

**Comment by megamindbrian** [comment]
I'll check that out maybe I missed that configuration.

**Comment by gabrielcsapo** [comment]
@megamindbrian thank you!

**Comment by gabrielcsapo** [comment]
@megamindbrian did you ever get the issue resolved with the proxy abilities?

**Comment by paxinos** [comment]
I'm not sure if this is a similar or related issue.   I am not user Docker.   But both machines are runing MacOSX.    I've setup local-npm on one machine and started it as:

`local-npm --url http://192.168.5.199:5080`

And, yes, that is the IP of that server.   On another server I've done:

`npm set registry http://192.168.5.199:5080`

and then tried something simple like this on that server: 

`npm i -g npm`

And eventually get the following as an error:

`npm ERR! code ECONNREFUSED`
`npm ERR! errno ECONNREFUSED`
`npm ERR! FetchError: request to http://127.0.0.1:5080/tarballs/npm/5.0.4.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:5080`
`npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)`
`npm ERR!     at emitOne (events.js:115:13)`
`...`

it seems like the '--url' is not being honored.   Any ideas of what I can try?   Thanks.  Pax.

**Comment by gabrielcsapo** [comment]
@paxinos --url is set as the entry point to local-npm 

```var localBase = options.url.replace(/:5080$/, ':' + port); // port is configurable```

what you want to set is --remote which will use the upstream correctly. 

If you are meaning to set the url of local-npm you are doing it correctly, but it doesn't look like you set the registry correctly because `npm set registry http://192.168.5.199:5080` didn't translate to the error you are getting `http://127.0.0.1:5080`

**Comment by megamindbrian** [comment]
Sorry, haven't have a chance to retest.  Been busy.  I'll hopefully get to
it this week.  If there are proxy options that should solve it, probably
would highlight that on the Readme.

**Comment by gabrielcsapo** [comment]
@megamindbrian 

This is the entry on the README, not sure if this is as complete as needed.

<img width="1035" alt="screen shot 2017-07-02 at 9 18 36 pm" src="https://user-images.githubusercontent.com/1854811/27777924-0a57498c-5f6c-11e7-97f8-d2ddedb2ccdd.png">

**Comment by paxinos** [comment]
Ok, what I'm trying to do is to use a local machine '192.168.5.199' as a
local npm caching proxy.    Primarily this is to allow me to install and
update npm packages on other machines when offline  (I will make sure the
packages are in the cache before going offline.)

Going by the instructions in 'protip 2', I used
     'npm --url http://192.168.5.199:5080' on the local server.

Per your email, I just tried
    'npm --remote http://192.168.5.199:5080'

On the client i'm doing:
   'npm set registry http://192.168.5.199:5080'

Whenever I try to install anything on the client, I get an ECONNREFUSED and
the url is always http://127.0.0.1:5080/....

Am I doing anything wrong?   Or does "ProTip 2" need some work?

Thanks,
pax.

http://www.siggraph.org/~pax/
http://www.linkedin.com/in/garrypaxinos

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by paxinos** [comment]
BTW, just to be complete -


Apotheosis:~ pax$ sudo npm set registry http://192.168.5.199:5080

Apotheosis:~ pax$ npm i -g npm

npm ERR! code ECONNREFUSED

npm ERR! errno ECONNREFUSED

npm ERR! FetchError: request to http://127.0.0.1:5080/tarballs/npm/5.0.4.tgz
failed, reason: connect ECONNREFUSED 127.0.0.1:5080

npm ERR!     at ClientRequest.req.on.err
(/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)

npm ERR!     at emitOne (events.js:115:13)

npm ERR!     at ClientRequest.emit (events.js:210:7)

npm ERR!     at Socket.socketErrorListener (_http_client.js:400:9)

http://www.siggraph.org/~pax/
http://www.linkedin.com/in/garrypaxinos

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by gabrielcsapo** [comment]
@paxinos, can you verify the version of local-npm? please 😊

**Comment by paxinos** [comment]
2.0.1

pulled from GitHub

theosis:npm pax$ local-npm --help

Options:

  -h, --help         this help message
[boolean]

  -p, --port         port                                        [default:
5080]

  -P, --pouch-port   pouchdb-server port                        [default:
16984]

  -l, --log          error|warn|info|debug                     [default:
"info"]

  -r, --remote       remote fullfatdb    [default: "
https://registry.npmjs.org"]

  -R, --remote-skim  remote skimdb      [default: "
https://replicate.npmjs.com"]

  -u, --url-base     base url it will be hosted on

                                              [default: "
http://127.0.0.1:5080"]

  --2.0.1            Show version number
[boolean]

  -d, --directory    directory to store data                     [default:
"./"]


Examples:

  local-npm -u http://foo.com -p 3000  run on port 3000 and visable at
foo.com


theosis:npm pax$





http://www.siggraph.org/~pax/
http://www.linkedin.com/in/garrypaxinos

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by gabrielcsapo** [comment]
let me look at creating a test case for this to replicate the behavior

**Comment by paxinos** [comment]
Greetings,

Just checking if you've had any time to look into this.

Thanks,
pax.

http://www.siggraph.org/~pax/
http://www.linkedin.com/in/garrypaxinos

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by megamindbrian** [comment]
I'll do it right now.

**Comment by megamindbrian** [comment]
Here is a working scenario:

```
## Using with Docker
Using local-npm with Docker can help speed up build times during development.
The awkward way to use this would be something like:
```
RUN local-npm && \
    npm set registry http://... && \
    npm set proxy .... && \
    npm install some packages etc ...
```

Running services inside of a Docker build command isn't really Docker's business.  The friendly scenario works better in this case:
```
local-npm --url=http://<network host or ip>:5080
```

And adding the npm registry/proxy commands to your Dockerfile:
```
RUN npm config set proxy http://<network host or ip>:5080
RUN npm config set proxy http://<network host or ip>:5080
RUN npm config set registry http://<network host or ip>:5080
RUN npm config set strict-ssl false
RUN npm install project dependencies ...
```

Can I PR this in README.md for you?

**Comment by megamindbrian** [comment]
I bet this is something @heroku could use to speed up build times on "buildpacks"

**Comment by gabrielcsapo** [comment]
@megamindbrian looks good to me, PR would be awesome!

**Comment by stonkeep** [comment]
I did the following :

npm config set proxy null npm config set https-proxy null
npm config set registry http://registry.npmjs.org/

**Comment by xtrinch** [comment]
None of the suggestions are working and I can't get npm to stop pointing to localhost;80

**Comment by darioajr** [comment]
This error occours to me without docker.

**Comment by rulatir** [comment]
This occurs to me in nave.
