### ISSUE TITLE
Cannot install @rosskevin/react-docgen@^3.0.0-beta9

### ISSUE THREAD

**Issue by Morton** [local-npm/local-npm#167]
I tried to install the dependency `@rosskevin/react-docgen@^3.0.0-beta9` today but it failed with HTTP 500. NPM succeeds installing the dependency without local-npm.

## Detailed Description
I am running local-npm 2.2.2 with `registry=http://127.0.0.1:5080` set in `~/.npmrc` . While running 
```
# npm i @rosskevin/react-docgen@^3.0.0-beta9
npm ERR! code E500
npm ERR! 500 Internal Server Error: @rosskevin/react-docgen@^3.0.0-beta9
```
I get a HTTP 500 error. Once I commented the registry-line in ~/.npmrc and run same npm-command the install works fine. Tried multiple times.

## Context
local-npm logs:
```
request:  GET,/@rosskevin%2freact-docgen,500,,1551.412192
request:  GET,/@rosskevin%2freact-docgen,500,,885.849964
request:  GET,/@rosskevin%2freact-docgen,500,,854.6937459999999
request:  GET,/@rosskevin%2freact-docgen,500,,1475.182819
```
npm debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/martinheller/.nvm/versions/node/v9.4.0/bin/node',
1 verbose cli   '/Users/martinheller/.nvm/versions/node/v9.4.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@rosskevin/react-docgen@^3.0.0-beta9' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose npm-session 2f2c77a933caf6a2
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 500 http://127.0.0.1:5080/@rosskevin%2freact-docgen 74162ms attempt #3
8 silly fetchPackageMetaData error for @rosskevin/react-docgen@^3.0.0-beta9 500 Internal Server Error: @rosskevin/react-docgen@^3.0.0-beta9
9 verbose stack Error: 500 Internal Server Error: @rosskevin/react-docgen@^3.0.0-beta9
9 verbose stack     at fetch.then.res (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/martinheller/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:756:18)
9 verbose stack     at tryOnImmediate (timers.js:717:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
10 verbose cwd /private/tmp/material-ui
11 verbose Darwin 17.3.0
12 verbose argv "/Users/martinheller/.nvm/versions/node/v9.4.0/bin/node" "/Users/martinheller/.nvm/versions/node/v9.4.0/bin/npm" "i" "@rosskevin/react-docgen@^3.0.0-beta9"
13 verbose node v9.4.0
14 verbose npm  v5.6.0
15 error code E500
16 error 500 Internal Server Error: @rosskevin/react-docgen@^3.0.0-beta9
17 verbose exit [ 1, true ]
```

## Environment
* Version used: local-npm 2.2.2
* Environment name and version: npm 5.6.0; node v9.4.0
* Operating System and version: MacOS 10.13.2 (17C205)

**Comment by gabrielcsapo** [comment]
Seems like the package is not being parsed correctly, `/@rosskevin%2freact-docgen` should be `/@rosskevin/freact-docgen@^3.0.0-beta9`
