### ISSUE TITLE
Can not install local-npm in Node 10.15.1 / npm 6.6.0

### ISSUE THREAD

**Issue by cakriwut** [local-npm/local-npm#178]
Can not install local-npm in Node 10.15.1 / npm 6.6.0

## Detailed Description
When I run installation command
```bash
npm install -g local-npm
```
the installation stop at leveldown@1.7.2 install error.
![image](https://user-images.githubusercontent.com/307755/52521252-331dca00-2caf-11e9-960d-9b2ac597ad77.png)

## Context
I am using following environment:
- OS : Windows Server 10
- Node : 10.15.1
- NPM : 6.6.0

I can build the source code, after I upgrade level package to version ^4.0.0. 
![image](https://user-images.githubusercontent.com/307755/52521267-724c1b00-2caf-11e9-9a8c-9a41c36ea809.png)

The server is running properly, however the
``` bash
node run coverage
```
doesn't pass all test cases. _I am not sure if the test coverage is having problem_

## Possible Implementation
- Update level package to version ^4.0.0

**Comment by rootlinux2** [comment]
I've the same ISSUE in node v11.10.1 and npm 6.9.0

**Comment by zsubzwary** [comment]
I think this is no longer maintained !  
# 😭😭

**Comment by klzsysy** [comment]
```sh
$ npm -v         
6.7.0
$ node -v
v11.10.1
```
```sh
36 warnings and 1 error generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/11.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/local-npm/node_modules/leveldown
gyp ERR! node -v v11.10.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/siyi/.npm/_logs/2019-04-20T08_16_18_933Z-debug.log
```

**Comment by gabrielcsapo** [comment]
Looks like https://github.com/local-npm/local-npm/pull/179 will solve this, I can wait a day or so if the PR doesn't get updated I can submit a PR and get that passing tests.

**Comment by gabrielcsapo** [comment]
Working on getting a clean build going to publish something under the 3.0.0-beta1 in the next couple days if anyone is interested in testing it out.

**Comment by youone** [comment]
I would be happy to test it.
